In [36]:
import pandas as pd

# attackqa.parquet

In [54]:
attackqa_parquet = pd.read_parquet(
    "https://huggingface.co/datasets/sambanovasystems/attackqa/resolve/main/attackqa.parquet",
    engine='pyarrow'
)

In [55]:
attackqa_parquet.head()

,question,thought,answer,document,subject_id,subject_name,subject_type,url,source,references,human_question,human_answer,field,relation_id,relation_name
0.0,What is a potential indicator of the 'T1539: S...,"To answer the question, I need to understand h...",A potential indicator of the 'T1539: Steal Web...,How data component 'Process Access' can be use...,T1539,Steal Web Session Cookie,techniques,https://attack.mitre.org/techniques/T1539,relationships_detects,None,False,False,None,None,Process Access
0.0,How can the 'Process Access' data component be...,"To answer the question, I need to understand h...",The 'Process Access' data component can be use...,How data component 'Process Access' can be use...,T1539,Steal Web Session Cookie,techniques,https://attack.mitre.org/techniques/T1539,relationships_detects,None,False,False,None,None,Process Access
0.0,What is the path to the maps file in the /proc...,"To answer the question, I need to know the loc...",The maps file is stored under the path /proc/<...,How data component 'Process Access' can be use...,T1033,System Owner/User Discovery,techniques,https://attack.mitre.org/techniques/T1033,relationships_detects,None,False,False,None,None,Process Access
0.0,What is the potential consequence of malicious...,"To answer the question, I need to consider the...",The potential consequence of malicious code in...,How data component 'Process Access' can be use...,T1055.005,Process Injection: Thread Local Storage,T1055,https://attack.mitre.org/techniques/T1055/005,relationships_detects,None,False,False,None,None,Process Access
0.0,What is an abnormal call to a higher privilege...,"To answer the question, I need to understand t...",An abnormal call to a higher privileged proces...,How data component 'Process Access' can be use...,T1559.003,Inter-Process Communication: XPC Services,T1559,https://attack.mitre.org/techniques/T1559/003,relationships_detects,None,False,False,None,None,Process Access

In [44]:
with pd.option_context('display.max_colwidth', None):
    display(attackqa_parquet[["question", "answer"]])

,question,answer
0,What is a potential indicator of the 'T1539: Steal Web Session Cookie' attack technique?,A potential indicator of the 'T1539: Steal Web Session Cookie' attack technique is monitoring for attempts by programs to inject into or dump browser process memory.
1,How can the 'Process Access' data component be used to detect the 'T1539: Steal Web Session Cookie' attack technique?,The 'Process Access' data component can be used to detect the 'T1539: Steal Web Session Cookie' attack technique by monitoring for attempts by programs to inject into or dump browser process memory.
3,What is the path to the maps file in the /proc filesystem for a process being analyzed?,"The maps file is stored under the path /proc/<pid>/maps, where the <pid> directory is the unique pid of the program being interrogated for such authentication data."
7,What is the potential consequence of malicious code injection into processes via TLS callbacks?,"The potential consequence of malicious code injection into processes via TLS callbacks is that it can evade process-based defenses and possibly elevate privileges, allowing attackers to gain unauthorized access and control."
8,What is an abnormal call to a higher privileged process?,"An abnormal call to a higher privileged process is a connection made by a user application to a VPN service, which is not a typical or expected behavior."
...,...,...
29981,How does attack software 'S0139: PowerDuke' use attack technique 'T1033: System Owner/User Discovery'?,PowerDuke has commands that enable it to obtain the current user's name and Security Identifier (SID).
29982,How does attack software 'S0139: PowerDuke' use attack technique 'T1124: System Time Discovery'?,"PowerDuke has commands to get the time the machine was built, the time, and the time zone."
29983,How does attack software 'S0139: PowerDuke' use attack technique 'T1059.003: Windows Command Shell'?,PowerDuke runs the command 'cmd.exe /c' and sends the output to its Command and Control (C2) server.
29984,How does attack software 'S1012: PowerLess' use attack technique 'T1560: Archive Collected Data'?,PowerLess uses the 'T1560: Archive Collected Data' technique by encrypting browser database files prior to exfiltration.
29985,How does attack software 'S1012: PowerLess' use attack technique 'T1217: Browser Information Discovery'?,PowerLess has a browser info stealer module that can read Chrome and Edge browser database files.

In [56]:
attackqa_human = attackqa_parquet[attackqa_parquet["human_answer"] == True].copy()
attackqa_human = attackqa_human.reset_index(drop=True)
attackqa_human = attackqa_human.dropna(subset=["question", "answer"])
print(f"Всего строк: {len(attackqa_human)}")
print(f"Строк с NaN в question: {attackqa_human['question'].isna().sum()}")
print(f"Строк с NaN в answer: {attackqa_human['answer'].isna().sum()}")
print(f"Строк с NaN в question ИЛИ answer: {attackqa_human[['question', 'answer']].isna().any(axis=1).sum()}")

Всего строк: 4994
Строк с NaN в question: 0
Строк с NaN в answer: 0
Строк с NaN в question ИЛИ answer: 0

In [46]:
attackqa_parquet.dropna(subset=["question", "answer"]).info()

<class 'pandas.DataFrame'>
Index: 25335 entries, 0 to 29985
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   question        25335 non-null  str
 1   thought         25335 non-null  str
 2   answer          25335 non-null  str
 3   document        25335 non-null  str
 4   subject_id      25335 non-null  str
 5   subject_name    25335 non-null  str
 6   subject_type    25335 non-null  str
 7   url             25335 non-null  str
 8   source          25335 non-null  str
 9   references      20341 non-null  object
 10  human_question  25335 non-null  bool
 11  human_answer    25335 non-null  bool
 12  field           5454 non-null   str
 13  relation_id     10756 non-null  str
 14  relation_name   13290 non-null  str
dtypes: bool(2), object(1), str(12)
memory usage: 23.2+ MB

In [47]:
attackqa_parquet.info()

<class 'pandas.DataFrame'>
Index: 25335 entries, 0 to 29985
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   question        25335 non-null  str
 1   thought         25335 non-null  str
 2   answer          25335 non-null  str
 3   document        25335 non-null  str
 4   subject_id      25335 non-null  str
 5   subject_name    25335 non-null  str
 6   subject_type    25335 non-null  str
 7   url             25335 non-null  str
 8   source          25335 non-null  str
 9   references      20341 non-null  object
 10  human_question  25335 non-null  bool
 11  human_answer    25335 non-null  bool
 12  field           5454 non-null   str
 13  relation_id     10756 non-null  str
 14  relation_name   13290 non-null  str
dtypes: bool(2), object(1), str(12)
memory usage: 23.2+ MB

In [14]:
attackqa_parquet.describe()

,question,thought,answer,document,subject_id,subject_name,subject_type,url,source,references,human_question,human_answer,field,relation_id,relation_name
count,25335,25335,25335,25335,25335,25335,25335,25335,25335,0,25335,25335,5454,10756,13290
unique,25335,22961,24941,17760,1503,1498,99,1503,25,0,2,2,1,718,816
top,What is a potential indicator of the 'T1539: S...,"To answer the question, I need to understand t...","Monitor network data for uncommon data flows, ...",How mitigation strategy 'M1015: Active Directo...,T1105,Ingress Tool Transfer,techniques,https://attack.mitre.org/techniques/T1105,relationships_uses_software,NaN,True,False,description,M1056,Process Creation
freq,1,256,48,6,371,371,8560,371,8534,NaN,17535,20341,5454,189,353

In [15]:
attackqa_parquet_human_answered = attackqa_parquet[attackqa_parquet['human_answer'] == True]
attackqa_parquet_human_answered.head()

,question,thought,answer,document,subject_id,subject_name,subject_type,url,source,references,human_question,human_answer,field,relation_id,relation_name
0.0,What campaigns used attack technique 'T1562.00...,"To answer the question, I need to know what ca...",The campaigns that used attack technique 'T156...,The campaigns that used attack technique 'T156...,T1562.001,Impair Defenses: Disable or Modify Tools,T1562,https://attack.mitre.org/techniques/T1562/001,relationships_campaigns_for_technique,None,True,True,None,None,None
0.0,What campaigns used attack technique 'T1136.00...,"To answer the question, I need to know what ca...",The campaigns that used attack technique 'T113...,The campaigns that used attack technique 'T113...,T1136.002,Create Account: Domain Account,T1136,https://attack.mitre.org/techniques/T1136/002,relationships_campaigns_for_technique,None,True,True,None,None,None
0.0,What campaigns used attack technique 'T1133: E...,"To answer the question, I need to know what ca...",The campaigns that used attack technique 'T113...,The campaigns that used attack technique 'T113...,T1133,External Remote Services,techniques,https://attack.mitre.org/techniques/T1133,relationships_campaigns_for_technique,None,True,True,None,None,None
0.0,What campaigns used attack technique 'T1070.00...,"To answer the question, I need to know what ca...",The campaigns that used attack technique 'T107...,The campaigns that used attack technique 'T107...,T1070.004,Indicator Removal: File Deletion,T1070,https://attack.mitre.org/techniques/T1070/004,relationships_campaigns_for_technique,None,True,True,None,None,None
0.0,What campaigns used attack technique 'T1105: I...,"To answer the question, I need to know what ca...",The campaigns that used attack technique 'T110...,The campaigns that used attack technique 'T110...,T1105,Ingress Tool Transfer,techniques,https://attack.mitre.org/techniques/T1105,relationships_campaigns_for_technique,None,True,True,None,None,None

In [16]:
attackqa_parquet_human_answered.info()

<class 'pandas.DataFrame'>
Index: 4994 entries, 0.0 to 0.0
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   question        4994 non-null   object
 1   thought         4994 non-null   object
 2   answer          4994 non-null   object
 3   document        4994 non-null   object
 4   subject_id      4994 non-null   object
 5   subject_name    4994 non-null   object
 6   subject_type    4994 non-null   object
 7   url             4994 non-null   object
 8   source          4994 non-null   object
 9   references      0 non-null      object
 10  human_question  4994 non-null   bool
 11  human_answer    4994 non-null   bool
 12  field           0 non-null      object
 13  relation_id     0 non-null      object
 14  relation_name   0 non-null      object
dtypes: bool(2), object(13)
memory usage: 556.0+ KB

### Length of questions

In [145]:
(attackqa_parquet_human_answered['question'].str.len().min(),
attackqa_parquet_human_answered['question'].str.len().mean().round(1),
attackqa_parquet_human_answered['question'].str.len().max())

(41, 88.9, 199)

### Length of answers

In [146]:
(attackqa_parquet_human_answered['answer'].str.len().min(),
attackqa_parquet_human_answered['answer'].str.len().mean().round(1),
attackqa_parquet_human_answered['answer'].str.len().max())

(64, 260.5, 6786)

### Words in questions

In [147]:
(attackqa_parquet_human_answered['question'].str.split().apply(len).min(),
attackqa_parquet_human_answered['question'].str.split().apply(len).mean().round(1),
attackqa_parquet_human_answered['question'].str.split().apply(len).max())

(6, 12.5, 28)

### Words in answers

In [148]:
(attackqa_parquet_human_answered['answer'].str.split().apply(len).min(),
attackqa_parquet_human_answered['answer'].str.split().apply(len).mean().round(1),
attackqa_parquet_human_answered['answer'].str.split().apply(len).max())

(10, 31.5, 741)

---

---

# cybersecurityQAAdataset.json

In [12]:
cybersecurityQAAdataset_json = pd.read_json("https://huggingface.co/datasets/Rowden/CybersecurityQAA/resolve/main/cybersecurityQAAdataset.json")

In [17]:
cybersecurityQAAdataset_json.head()

,vars,assert
0,{'question': 'How can I ensure that my busines...,"[{'type': 'llm-rubric', 'value': 'The answer c..."
1,{'question': 'Explain the importance of mainta...,"[{'type': 'llm-rubric', 'value': 'The answer c..."
2,{'question': 'How can small businesses protect...,"[{'type': 'llm-rubric', 'value': 'The answer h..."
3,{'question': 'What are the recommended practic...,"[{'type': 'llm-rubric', 'value': 'The answer a..."
4,{'question': 'What steps should be taken to ma...,"[{'type': 'llm-rubric', 'value': 'The answer c..."

In [18]:
cybersecurityQAAdataset = pd.json_normalize(cybersecurityQAAdataset_json['vars'])
cybersecurityQAAdataset.head()

,question,answer,evidence,sourceURL,theme,question_type,target_audience,reviewed_by_human,edited_by_human,reviewed_by_expert,edited_by_expert,expert_score,expert_comment
0,How can I ensure that my business's network ac...,To ensure your business's network access is re...,1.3.1 Inbound traffic to the CDE is restricted...,n/a,Network_Security,Advice,small_business,TRUE,TRUE,TRUE,FALSE,1,
1,Explain the importance of maintaining an accur...,Maintaining an accurate network diagram is cru...,1.2.3 An accurate network diagram(s) is mainta...,n/a,Network_Security,Clarification,small_business,TRUE,TRUE,TRUE,FALSE,1,
2,How can small businesses protect passwords for...,Small businesses should ensure that passwords ...,Good Practice: Changing these values due to su...,Payment Card Industry Data Security Standard: ...,Authentication_User_Access_and_Controls,Advice,small_business,TRUE,FALSE,TRUE,FALSE,2,
3,What are the recommended practices for physica...,Media containing cardholder data should be phy...,9.4.1 All media with cardholder data is physic...,Payment Card Industry Data Security Standard: ...,Data_Storage_and_Back_Up,Advice,small_business,TRUE,FALSE,TRUE,FALSE,1,
4,What steps should be taken to manage visitor a...,Visitor access should be authorized before ent...,9.3.2 Procedures are implemented for authorizi...,Payment Card Industry Data Security Standard: ...,Security_Operations_and_Incident_Management,Advice,small_business,TRUE,FALSE,TRUE,FALSE,1,

In [19]:
with pd.option_context('display.max_colwidth', None):
    display(cybersecurityQAAdataset[["question", "answer"]].head())

,question,answer
0,How can I ensure that my business's network access is restricted as per PCI DSS requirements?,"To ensure your business's network access is restricted according to PCI DSS requirements, you should ensure that inbound traffic to the Cardholder Data Environment (CDE) is restricted to only necessary traffic, and all other traffic is specifically denied. Similarly, outbound traffic from the CDE should also be restricted to necessary communications only. Implement Network Security Controls (NSCs) between all wireless networks and the CDE, and ensure that system components storing cardholder data are not directly accessible from untrusted networks. Additionally, anti-spoofing measures should be implemented to block forged IP addresses."
1,Explain the importance of maintaining an accurate network diagram according to PCI DSS.,"Maintaining an accurate network diagram is crucial according to PCI DSS because it helps prevent network connections and devices from being overlooked, which can leave them unsecured and vulnerable. It ensures that all connections to and from the Cardholder Data Environment (CDE) are identified, including those providing security, management, or maintenance services. This helps verify PCI DSS scope by identifying systems connecting to and from the CDE and assists in maintaining secure configurations."
2,How can small businesses protect passwords for application and system accounts from unauthorized use?,"Small businesses should ensure that passwords and passphrases are not hard coded in scripts, configuration files, or custom source code. They should use tools like password vaults to manage and secure authentication factors for application and system accounts."
3,What are the recommended practices for physically securing media with cardholder data?,"Media containing cardholder data should be physically secured to prevent unauthorized access. This includes using secure storage facilities and regularly reviewing the security of storage locations. Additionally, records of media movements should be maintained and approved by management."
4,What steps should be taken to manage visitor access to sensitive areas within a cardholder data environment (CDE)?,"Visitor access should be authorized before entering the CDE, and visitors should be escorted at all times. They must be clearly identified with badges that distinguish them from personnel, and these badges should expire after a specific period."

In [153]:
cybersecurityQAAdataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1563 entries, 0 to 1562
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   question            1563 non-null   str
 1   answer              1563 non-null   str
 2   evidence            1563 non-null   str
 3   sourceURL           1563 non-null   str
 4   theme               1563 non-null   str
 5   question_type       1563 non-null   str
 6   target_audience     1563 non-null   str
 7   reviewed_by_human   1563 non-null   str
 8   edited_by_human     1563 non-null   str
 9   reviewed_by_expert  1563 non-null   str
 10  edited_by_expert    1563 non-null   str
 11  expert_score        1563 non-null   str
 12  expert_comment      1563 non-null   str
dtypes: str(13)
memory usage: 158.9 KB

In [154]:
cybersecurityQAAdataset.describe()

,question,answer,evidence,sourceURL,theme,question_type,target_audience,reviewed_by_human,edited_by_human,reviewed_by_expert,edited_by_expert,expert_score,expert_comment
count,1563,1563,1563,1563,1563,1563,1563,1563,1563,1563,1563,1563,1563
unique,1557,1562,1485,174,14,4,3,2,2,3,3,3,45
top,What is lateral movement in the context of net...,Using a broken or risky cryptographic algorith...,"<p>If you suspect your PC, tablet or phone has...",,Security_Operations_and_Incident_Management,Advice,cyber_security_professional,TRUE,FALSE,,,,
freq,2,2,4,1134,366,567,783,1492,1343,942,926,1118,1513

In [155]:
cybersecurityQAAdataset['expert_score'] = pd.to_numeric(cybersecurityQAAdataset['expert_score'])
cybersecurityQAAdataset['reviewed_by_expert'] = cybersecurityQAAdataset['reviewed_by_expert'].astype(str).map({'TRUE': True, 'FALSE': False, '': False}).fillna(False)

cybersecurityQAAdataset['reviewed_by_expert'].unique()

array([ True, False])

In [156]:
cybersecurityQAAdataset_only_reviewed_by_expert = cybersecurityQAAdataset[cybersecurityQAAdataset['reviewed_by_expert'] == True]

### Length of questions

In [157]:
(cybersecurityQAAdataset_only_reviewed_by_expert['question'].str.len().min(),
cybersecurityQAAdataset_only_reviewed_by_expert['question'].str.len().mean().round(1),
cybersecurityQAAdataset_only_reviewed_by_expert['question'].str.len().max())

(30, 96.9, 188)

### Length of answers

In [158]:
(cybersecurityQAAdataset_only_reviewed_by_expert['answer'].str.len().min(),
cybersecurityQAAdataset_only_reviewed_by_expert['answer'].str.len().mean().round(1),
cybersecurityQAAdataset_only_reviewed_by_expert['answer'].str.len().max())

(17, 367.2, 1064)

In [159]:
cybersecurityQAAdataset_only_reviewed_by_expert['expert_score'].unique()

array([1., 2.])

### Words in questions

In [160]:
(cybersecurityQAAdataset_only_reviewed_by_expert['question'].str.split().apply(len).min(),
cybersecurityQAAdataset_only_reviewed_by_expert['question'].str.split().apply(len).mean().round(1),
cybersecurityQAAdataset_only_reviewed_by_expert['question'].str.split().apply(len).max())

(5, 15.5, 32)

### Words in answers

In [161]:
(cybersecurityQAAdataset_only_reviewed_by_expert['answer'].str.split().apply(len).min(),
cybersecurityQAAdataset_only_reviewed_by_expert['answer'].str.split().apply(len).mean().round(1),
cybersecurityQAAdataset_only_reviewed_by_expert['answer'].str.split().apply(len).max())

(3, 53.3, 143)

---

---

# cybersecurity_qa

In [162]:
cybersecurity_qa_json = pd.read_json(
    "https://huggingface.co/datasets/mariiazhiv/cybersecurity_qa/resolve/main/cybersecurity_qa.jsonl",
    lines=True
)

In [163]:
cybersecurity_qa_json.head()

,instruction,input,output
0,What is cybersecurity's primary purpose?,,Cybersecurity's primary purpose is to protect ...
1,Define cybersecurity,,"The term ""cybersecurity"" refers to the collect..."
2,List the basic elements of cybersecurity.,,Here are the basic elements of cybersecurity: ...
3,What is cryptography?,,Cryptography is the cybersecurity domain that ...
4,Explain the difference between an IDS and an IPS.,,IDS stands for Intrusion Detection System and ...

In [164]:
cybersecurity_qa_json.info()

<class 'pandas.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  502 non-null    str
 1   input        502 non-null    str
 2   output       502 non-null    str
dtypes: str(3)
memory usage: 11.9 KB

### Length of questions

In [165]:
(cybersecurity_qa_json['instruction'].str.len().min(),
cybersecurity_qa_json['instruction'].str.len().mean().round(1),
cybersecurity_qa_json['instruction'].str.len().max())

(11, 56.0, 235)

### Length of answers

In [166]:
(cybersecurity_qa_json['output'].str.len().min(),
cybersecurity_qa_json['output'].str.len().mean().round(1),
cybersecurity_qa_json['output'].str.len().max())

(67, 428.3, 2804)

### Words in questions

In [167]:
(cybersecurity_qa_json['instruction'].str.split().apply(len).min(),
cybersecurity_qa_json['instruction'].str.split().apply(len).mean().round(1),
cybersecurity_qa_json['instruction'].str.split().apply(len).max())

(2, 8.9, 36)

### Words in answers

In [168]:
(cybersecurity_qa_json['output'].str.split().apply(len).min(),
cybersecurity_qa_json['output'].str.split().apply(len).mean().round(1),
cybersecurity_qa_json['output'].str.split().apply(len).max())

(7, 63.3, 443)

---

---

## Saving dataframes

In [172]:
# attackqa_parquet_human_answered[['question', 'answer']].to_csv("attackqa_parquet_human_answered.csv")

In [174]:
# cybersecurityQAAdataset_only_reviewed_by_expert[['question', 'answer', 'expert_score']]\
#     .to_csv("cybersecurityQAAdataset_only_reviewed_by_expert.csv")

In [178]:
# cybersecurity_qa_updated_column_names = cybersecurity_qa_json.rename(columns={
#     'instruction': 'question',
#     'output': 'answer'
# })
# cybersecurity_qa_updated_column_names[['question', 'answer']].to_csv("cybersecurity_qa_updated_column_names.csv")

In [179]:
# attackqa_parquet[['question', 'answer']].drop_duplicates().to_csv("attackqa_parquet_RAW.csv")

In [188]:
# cybersecurityQAAdataset[['question', 'answer']].drop_duplicates().to_csv("cybersecurityQAAdataset_RAW.csv")

In [189]:
# cybersecurity_qa_updated_column_names[['question', 'answer']].drop_duplicates().to_csv("cybersecurity_qa_RAW.csv")

---

## Construct full pre-dataser

In [190]:
first_df = pd.read_csv("attackqa_parquet_human_answered.csv")

In [191]:
second_df = pd.read_csv("cybersecurityQAAdataset_only_reviewed_by_expert.csv")

In [192]:
third_df = pd.read_csv("cybersecurity_qa_updated_column_names.csv")

In [194]:
first_df.head()

,Unnamed: 0,question,answer
0,1.421378e-76,What campaigns used attack technique 'T1562.00...,The campaigns that used attack technique 'T156...
1,2.917960e-14,What campaigns used attack technique 'T1136.00...,The campaigns that used attack technique 'T113...
2,1.614106e+132,What campaigns used attack technique 'T1133: E...,The campaigns that used attack technique 'T113...
3,2.001464e-23,What campaigns used attack technique 'T1070.00...,The campaigns that used attack technique 'T107...
4,5.037346e+180,What campaigns used attack technique 'T1105: I...,The campaigns that used attack technique 'T110...